# Generated by Django 5.2.15 on 2026-06-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=3)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('unequal', 'Unequal'), ('percentage', 'Percentage')], default='equal', max_length=20)),
                ('is_reversal', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv_import', 'CSV Import')], default='manual', max_length=20)),
                ('raw_csv_row', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
                ('reversed_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='expenses.expense')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.group'),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_flags', 'Completed with Flags')], default='processing', max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='expenses.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_row_number', models.IntegerField()),
                ('raw_row_data', models.JSONField()),
                ('anomaly_type', models.CharField(choices=[('DUPLICATE_EXPENSE', 'Duplicate Expense'), ('SETTLEMENT_MISCLASSIFIED_AS_EXPENSE', 'Settlement Misclassified as Expense'), ('ZERO_AMOUNT', 'Zero Amount'), ('CURRENCY_MISSING', 'Currency Missing'), ('CURRENCY_CONVERSION_APPLIED', 'Currency Conversion Applied'), ('NEGATIVE_AMOUNT_REFUND', 'Negative Amount Refund'), ('DATE_FORMAT_AMBIGUOUS', 'Date Format Ambiguous'), ('DATE_MISSING_YEAR', 'Date Missing Year'), ('NAME_ALIAS_RESOLVED', 'Name Alias Resolved'), ('AMOUNT_FORMAT_CLEANED', 'Amount Format Cleaned'), ('SPLIT_DETAILS_PARSED_VIA_AI', 'Split Details Parsed via AI'), ('SPLIT_DETAILS_PARSE_FAILED_FALLBACK', 'Split Details Parse Failed Fallback'), ('SPLIT_NOTE_CONTRADICTION', 'Split Note Contradiction'), ('NON_MEMBER_IN_SPLIT', 'Non-Member in Split'), ('UNPARSEABLE_ROW', 'Unparseable Row')], max_length=50)),
                ('description', models.TextField()),
                ('action_taken', models.TextField()),
                ('status', models.CharField(choices=[('auto_resolved', 'Auto Resolved'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='needs_review', max_length=30)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='expenses.importbatch')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.importbatch'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv_import', 'CSV Import')], default='manual', max_length=20)),
                ('raw_csv_row', models.JSONField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='expenses.importbatch')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField()),
                ('left_at', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='expenses.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
